alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
pushgateway:
  enabled: false
server:
  ingress:
    enabled: true
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 256Mi
  persistentVolume:
    size: 4Gi
  extraArgs:
    storage.tsdb.retention.size: 128MB