{{- if .Values.clusterRole.rules -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "external-mdns.fullname" . }}
  labels:
    {{- include "external-mdns.labels" . | nindent 4 }}
  {{- with .Values.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.clusterRole.rules }}
rules:
  {{ toYaml . | nindent 4}}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: {{ include "external-mdns.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "external-mdns.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "external-mdns.fullname" . }}
  namespace: {{ .Values.namespace }}
{{- end }}
