ingress:
  enabled: true
grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s"
sidecar:
  dashboards:
    enabled: true
    searchNamespace: ALL
    labelValue: "1"
resources:
  requests:
    memory: 256Mi
  limits:
    memory: 256Mi
podAnnotations:
  prometheus.io/scrape: "false"
service:
  annotations:
    prometheus.io/scrape: "false"