ingress:
  hosts:
  - grafana.fuf.me
grafana.ini:
  domain: grafana.fuf.me
  auth.anonymous:
    enabled: true
    org_name: Main Org.
    org_role: Editor
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      url: http://prometheus-server.service-metrics-local-v1:80
      isDefault: true