ingress:
  hosts:
  - grafana.fuf.me
grafana.ini:
  domain: grafana.fuf.me
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      url: http://prometheus-server.service-metrics-local-v1:80
      isDefault: true