helmDefaults:
  wait: true
  atomic: true
  verify: false # necessary as this is a local chart

environments:
  local: {}
  development: {}

releases:
  - name: app
    namespace: service-mdns-{{ .Environment.Name }}-v1
    createNamespace: true
    chart: ../helm/charts/external-mdns
    values:
    - ../helm/values/external-mdns/common.yaml
    - ../helm/values/external-mdns/{{ .Environment.Name }}.yaml