repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

helmDefaults:
  wait: true
  verify: false
  atomic: true

environments:
  local: {}
  development: {}

releases:
  - name: prometheus
    namespace: service-metrics-{{ .Environment.Name }}-v1
    chart: prometheus-community/prometheus
    createNamespace: true
    values:
    - ../helm/values/prometheus/common.yaml
    - ../helm/values/prometheus/{{ .Environment.Name }}.yaml
