repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

helmDefaults:
  wait: true
  verify: false
  atomic: true

environments:
  local: {}
  development: {}

releases:
  - name: snmp-exporter
    namespace: exporter-snmp-{{ .Environment.Name }}-v1
    chart: prometheus-community/prometheus-snmp-exporter
    createNamespace: true
    values:
    - ../helm/values/snmp/common.yaml
  - name: grafana-dashboard
    namespace: exporter-snmp-{{ .Environment.Name }}-v1
    chart: ../helm/charts/grafana-dashboard
